/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU.impl;

import fr.n7.jEU.AllocateurConnaissance;
import fr.n7.jEU.Connaissance;
import fr.n7.jEU.JEUPackage;
import fr.n7.jEU.condition;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Allocateur Connaissance</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jEU.impl.AllocateurConnaissanceImpl#getConnaissanceAlloue <em>Connaissance Alloue</em>}</li>
 *   <li>{@link fr.n7.jEU.impl.AllocateurConnaissanceImpl#isEstConditionne <em>Est Conditionne</em>}</li>
 *   <li>{@link fr.n7.jEU.impl.AllocateurConnaissanceImpl#getConditionAllocution <em>Condition Allocution</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AllocateurConnaissanceImpl extends MinimalEObjectImpl.Container implements AllocateurConnaissance
{
  /**
   * The cached value of the '{@link #getConnaissanceAlloue() <em>Connaissance Alloue</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConnaissanceAlloue()
   * @generated
   * @ordered
   */
  protected Connaissance connaissanceAlloue;

  /**
   * The default value of the '{@link #isEstConditionne() <em>Est Conditionne</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEstConditionne()
   * @generated
   * @ordered
   */
  protected static final boolean EST_CONDITIONNE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isEstConditionne() <em>Est Conditionne</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEstConditionne()
   * @generated
   * @ordered
   */
  protected boolean estConditionne = EST_CONDITIONNE_EDEFAULT;

  /**
   * The cached value of the '{@link #getConditionAllocution() <em>Condition Allocution</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConditionAllocution()
   * @generated
   * @ordered
   */
  protected condition conditionAllocution;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AllocateurConnaissanceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JEUPackage.Literals.ALLOCATEUR_CONNAISSANCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Connaissance getConnaissanceAlloue()
  {
    if (connaissanceAlloue != null && connaissanceAlloue.eIsProxy())
    {
      InternalEObject oldConnaissanceAlloue = (InternalEObject)connaissanceAlloue;
      connaissanceAlloue = (Connaissance)eResolveProxy(oldConnaissanceAlloue);
      if (connaissanceAlloue != oldConnaissanceAlloue)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, JEUPackage.ALLOCATEUR_CONNAISSANCE__CONNAISSANCE_ALLOUE, oldConnaissanceAlloue, connaissanceAlloue));
      }
    }
    return connaissanceAlloue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Connaissance basicGetConnaissanceAlloue()
  {
    return connaissanceAlloue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConnaissanceAlloue(Connaissance newConnaissanceAlloue)
  {
    Connaissance oldConnaissanceAlloue = connaissanceAlloue;
    connaissanceAlloue = newConnaissanceAlloue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JEUPackage.ALLOCATEUR_CONNAISSANCE__CONNAISSANCE_ALLOUE, oldConnaissanceAlloue, connaissanceAlloue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isEstConditionne()
  {
    return estConditionne;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEstConditionne(boolean newEstConditionne)
  {
    boolean oldEstConditionne = estConditionne;
    estConditionne = newEstConditionne;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JEUPackage.ALLOCATEUR_CONNAISSANCE__EST_CONDITIONNE, oldEstConditionne, estConditionne));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public condition getConditionAllocution()
  {
    return conditionAllocution;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetConditionAllocution(condition newConditionAllocution, NotificationChain msgs)
  {
    condition oldConditionAllocution = conditionAllocution;
    conditionAllocution = newConditionAllocution;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JEUPackage.ALLOCATEUR_CONNAISSANCE__CONDITION_ALLOCUTION, oldConditionAllocution, newConditionAllocution);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConditionAllocution(condition newConditionAllocution)
  {
    if (newConditionAllocution != conditionAllocution)
    {
      NotificationChain msgs = null;
      if (conditionAllocution != null)
        msgs = ((InternalEObject)conditionAllocution).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JEUPackage.ALLOCATEUR_CONNAISSANCE__CONDITION_ALLOCUTION, null, msgs);
      if (newConditionAllocution != null)
        msgs = ((InternalEObject)newConditionAllocution).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JEUPackage.ALLOCATEUR_CONNAISSANCE__CONDITION_ALLOCUTION, null, msgs);
      msgs = basicSetConditionAllocution(newConditionAllocution, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JEUPackage.ALLOCATEUR_CONNAISSANCE__CONDITION_ALLOCUTION, newConditionAllocution, newConditionAllocution));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JEUPackage.ALLOCATEUR_CONNAISSANCE__CONDITION_ALLOCUTION:
        return basicSetConditionAllocution(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JEUPackage.ALLOCATEUR_CONNAISSANCE__CONNAISSANCE_ALLOUE:
        if (resolve) return getConnaissanceAlloue();
        return basicGetConnaissanceAlloue();
      case JEUPackage.ALLOCATEUR_CONNAISSANCE__EST_CONDITIONNE:
        return isEstConditionne();
      case JEUPackage.ALLOCATEUR_CONNAISSANCE__CONDITION_ALLOCUTION:
        return getConditionAllocution();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JEUPackage.ALLOCATEUR_CONNAISSANCE__CONNAISSANCE_ALLOUE:
        setConnaissanceAlloue((Connaissance)newValue);
        return;
      case JEUPackage.ALLOCATEUR_CONNAISSANCE__EST_CONDITIONNE:
        setEstConditionne((Boolean)newValue);
        return;
      case JEUPackage.ALLOCATEUR_CONNAISSANCE__CONDITION_ALLOCUTION:
        setConditionAllocution((condition)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JEUPackage.ALLOCATEUR_CONNAISSANCE__CONNAISSANCE_ALLOUE:
        setConnaissanceAlloue((Connaissance)null);
        return;
      case JEUPackage.ALLOCATEUR_CONNAISSANCE__EST_CONDITIONNE:
        setEstConditionne(EST_CONDITIONNE_EDEFAULT);
        return;
      case JEUPackage.ALLOCATEUR_CONNAISSANCE__CONDITION_ALLOCUTION:
        setConditionAllocution((condition)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JEUPackage.ALLOCATEUR_CONNAISSANCE__CONNAISSANCE_ALLOUE:
        return connaissanceAlloue != null;
      case JEUPackage.ALLOCATEUR_CONNAISSANCE__EST_CONDITIONNE:
        return estConditionne != EST_CONDITIONNE_EDEFAULT;
      case JEUPackage.ALLOCATEUR_CONNAISSANCE__CONDITION_ALLOCUTION:
        return conditionAllocution != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (estConditionne: ");
    result.append(estConditionne);
    result.append(')');
    return result.toString();
  }

} //AllocateurConnaissanceImpl
