/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU.impl;

import fr.n7.jEU.Connaissance;
import fr.n7.jEU.JEUPackage;
import fr.n7.jEU.Joueur;
import fr.n7.jEU.Lieu;
import fr.n7.jEU.Objet;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Joueur</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jEU.impl.JoueurImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.jEU.impl.JoueurImpl#getConnaissance <em>Connaissance</em>}</li>
 *   <li>{@link fr.n7.jEU.impl.JoueurImpl#getTailleinventaire <em>Tailleinventaire</em>}</li>
 *   <li>{@link fr.n7.jEU.impl.JoueurImpl#getObjets <em>Objets</em>}</li>
 *   <li>{@link fr.n7.jEU.impl.JoueurImpl#getLieu <em>Lieu</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JoueurImpl extends MinimalEObjectImpl.Container implements Joueur
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getConnaissance() <em>Connaissance</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConnaissance()
   * @generated
   * @ordered
   */
  protected EList<Connaissance> connaissance;

  /**
   * The default value of the '{@link #getTailleinventaire() <em>Tailleinventaire</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTailleinventaire()
   * @generated
   * @ordered
   */
  protected static final int TAILLEINVENTAIRE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTailleinventaire() <em>Tailleinventaire</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTailleinventaire()
   * @generated
   * @ordered
   */
  protected int tailleinventaire = TAILLEINVENTAIRE_EDEFAULT;

  /**
   * The cached value of the '{@link #getObjets() <em>Objets</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjets()
   * @generated
   * @ordered
   */
  protected EList<Objet> objets;

  /**
   * The cached value of the '{@link #getLieu() <em>Lieu</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLieu()
   * @generated
   * @ordered
   */
  protected Lieu lieu;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JoueurImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JEUPackage.Literals.JOUEUR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JEUPackage.JOUEUR__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Connaissance> getConnaissance()
  {
    if (connaissance == null)
    {
      connaissance = new EObjectResolvingEList<Connaissance>(Connaissance.class, this, JEUPackage.JOUEUR__CONNAISSANCE);
    }
    return connaissance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getTailleinventaire()
  {
    return tailleinventaire;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTailleinventaire(int newTailleinventaire)
  {
    int oldTailleinventaire = tailleinventaire;
    tailleinventaire = newTailleinventaire;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JEUPackage.JOUEUR__TAILLEINVENTAIRE, oldTailleinventaire, tailleinventaire));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Objet> getObjets()
  {
    if (objets == null)
    {
      objets = new EObjectResolvingEList<Objet>(Objet.class, this, JEUPackage.JOUEUR__OBJETS);
    }
    return objets;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Lieu getLieu()
  {
    if (lieu != null && lieu.eIsProxy())
    {
      InternalEObject oldLieu = (InternalEObject)lieu;
      lieu = (Lieu)eResolveProxy(oldLieu);
      if (lieu != oldLieu)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, JEUPackage.JOUEUR__LIEU, oldLieu, lieu));
      }
    }
    return lieu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Lieu basicGetLieu()
  {
    return lieu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLieu(Lieu newLieu)
  {
    Lieu oldLieu = lieu;
    lieu = newLieu;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JEUPackage.JOUEUR__LIEU, oldLieu, lieu));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JEUPackage.JOUEUR__NAME:
        return getName();
      case JEUPackage.JOUEUR__CONNAISSANCE:
        return getConnaissance();
      case JEUPackage.JOUEUR__TAILLEINVENTAIRE:
        return getTailleinventaire();
      case JEUPackage.JOUEUR__OBJETS:
        return getObjets();
      case JEUPackage.JOUEUR__LIEU:
        if (resolve) return getLieu();
        return basicGetLieu();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JEUPackage.JOUEUR__NAME:
        setName((String)newValue);
        return;
      case JEUPackage.JOUEUR__CONNAISSANCE:
        getConnaissance().clear();
        getConnaissance().addAll((Collection<? extends Connaissance>)newValue);
        return;
      case JEUPackage.JOUEUR__TAILLEINVENTAIRE:
        setTailleinventaire((Integer)newValue);
        return;
      case JEUPackage.JOUEUR__OBJETS:
        getObjets().clear();
        getObjets().addAll((Collection<? extends Objet>)newValue);
        return;
      case JEUPackage.JOUEUR__LIEU:
        setLieu((Lieu)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JEUPackage.JOUEUR__NAME:
        setName(NAME_EDEFAULT);
        return;
      case JEUPackage.JOUEUR__CONNAISSANCE:
        getConnaissance().clear();
        return;
      case JEUPackage.JOUEUR__TAILLEINVENTAIRE:
        setTailleinventaire(TAILLEINVENTAIRE_EDEFAULT);
        return;
      case JEUPackage.JOUEUR__OBJETS:
        getObjets().clear();
        return;
      case JEUPackage.JOUEUR__LIEU:
        setLieu((Lieu)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JEUPackage.JOUEUR__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case JEUPackage.JOUEUR__CONNAISSANCE:
        return connaissance != null && !connaissance.isEmpty();
      case JEUPackage.JOUEUR__TAILLEINVENTAIRE:
        return tailleinventaire != TAILLEINVENTAIRE_EDEFAULT;
      case JEUPackage.JOUEUR__OBJETS:
        return objets != null && !objets.isEmpty();
      case JEUPackage.JOUEUR__LIEU:
        return lieu != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", tailleinventaire: ");
    result.append(tailleinventaire);
    result.append(')');
    return result.toString();
  }

} //JoueurImpl
