/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU.impl;

import fr.n7.jEU.Interaction;
import fr.n7.jEU.JEUPackage;
import fr.n7.jEU.Personne;
import fr.n7.jEU.typeactivite;
import fr.n7.jEU.typevisibilite;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Personne</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jEU.impl.PersonneImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.jEU.impl.PersonneImpl#getVisibilite <em>Visibilite</em>}</li>
 *   <li>{@link fr.n7.jEU.impl.PersonneImpl#getActivite <em>Activite</em>}</li>
 *   <li>{@link fr.n7.jEU.impl.PersonneImpl#getInteraction <em>Interaction</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PersonneImpl extends MinimalEObjectImpl.Container implements Personne
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getVisibilite() <em>Visibilite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibilite()
   * @generated
   * @ordered
   */
  protected static final typevisibilite VISIBILITE_EDEFAULT = typevisibilite.VISIBLE;

  /**
   * The cached value of the '{@link #getVisibilite() <em>Visibilite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibilite()
   * @generated
   * @ordered
   */
  protected typevisibilite visibilite = VISIBILITE_EDEFAULT;

  /**
   * The default value of the '{@link #getActivite() <em>Activite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActivite()
   * @generated
   * @ordered
   */
  protected static final typeactivite ACTIVITE_EDEFAULT = typeactivite.ACTIF;

  /**
   * The cached value of the '{@link #getActivite() <em>Activite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActivite()
   * @generated
   * @ordered
   */
  protected typeactivite activite = ACTIVITE_EDEFAULT;

  /**
   * The cached value of the '{@link #getInteraction() <em>Interaction</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInteraction()
   * @generated
   * @ordered
   */
  protected Interaction interaction;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PersonneImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JEUPackage.Literals.PERSONNE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JEUPackage.PERSONNE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public typevisibilite getVisibilite()
  {
    return visibilite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVisibilite(typevisibilite newVisibilite)
  {
    typevisibilite oldVisibilite = visibilite;
    visibilite = newVisibilite == null ? VISIBILITE_EDEFAULT : newVisibilite;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JEUPackage.PERSONNE__VISIBILITE, oldVisibilite, visibilite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public typeactivite getActivite()
  {
    return activite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setActivite(typeactivite newActivite)
  {
    typeactivite oldActivite = activite;
    activite = newActivite == null ? ACTIVITE_EDEFAULT : newActivite;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JEUPackage.PERSONNE__ACTIVITE, oldActivite, activite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Interaction getInteraction()
  {
    return interaction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInteraction(Interaction newInteraction, NotificationChain msgs)
  {
    Interaction oldInteraction = interaction;
    interaction = newInteraction;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JEUPackage.PERSONNE__INTERACTION, oldInteraction, newInteraction);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInteraction(Interaction newInteraction)
  {
    if (newInteraction != interaction)
    {
      NotificationChain msgs = null;
      if (interaction != null)
        msgs = ((InternalEObject)interaction).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JEUPackage.PERSONNE__INTERACTION, null, msgs);
      if (newInteraction != null)
        msgs = ((InternalEObject)newInteraction).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JEUPackage.PERSONNE__INTERACTION, null, msgs);
      msgs = basicSetInteraction(newInteraction, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JEUPackage.PERSONNE__INTERACTION, newInteraction, newInteraction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JEUPackage.PERSONNE__INTERACTION:
        return basicSetInteraction(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JEUPackage.PERSONNE__NAME:
        return getName();
      case JEUPackage.PERSONNE__VISIBILITE:
        return getVisibilite();
      case JEUPackage.PERSONNE__ACTIVITE:
        return getActivite();
      case JEUPackage.PERSONNE__INTERACTION:
        return getInteraction();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JEUPackage.PERSONNE__NAME:
        setName((String)newValue);
        return;
      case JEUPackage.PERSONNE__VISIBILITE:
        setVisibilite((typevisibilite)newValue);
        return;
      case JEUPackage.PERSONNE__ACTIVITE:
        setActivite((typeactivite)newValue);
        return;
      case JEUPackage.PERSONNE__INTERACTION:
        setInteraction((Interaction)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JEUPackage.PERSONNE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case JEUPackage.PERSONNE__VISIBILITE:
        setVisibilite(VISIBILITE_EDEFAULT);
        return;
      case JEUPackage.PERSONNE__ACTIVITE:
        setActivite(ACTIVITE_EDEFAULT);
        return;
      case JEUPackage.PERSONNE__INTERACTION:
        setInteraction((Interaction)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JEUPackage.PERSONNE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case JEUPackage.PERSONNE__VISIBILITE:
        return visibilite != VISIBILITE_EDEFAULT;
      case JEUPackage.PERSONNE__ACTIVITE:
        return activite != ACTIVITE_EDEFAULT;
      case JEUPackage.PERSONNE__INTERACTION:
        return interaction != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", visibilite: ");
    result.append(visibilite);
    result.append(", activite: ");
    result.append(activite);
    result.append(')');
    return result.toString();
  }

} //PersonneImpl
