/**
 * generated by Xtext 2.17.1
 */
package fr.n7;

import fr.n7.JEUStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class JEUStandaloneSetup extends JEUStandaloneSetupGenerated {
  public static void doSetup() {
    new JEUStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
