/*
 * generated by Xtext 2.17.1
 */
package fr.n7.parser.antlr;

import com.google.inject.Inject;
import fr.n7.parser.antlr.internal.InternalJEUParser;
import fr.n7.services.JEUGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class JEUParser extends AbstractAntlrParser {

	@Inject
	private JEUGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJEUParser createParser(XtextTokenStream stream) {
		return new InternalJEUParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Jeu";
	}

	public JEUGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JEUGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
