/*
 * generated by Xtext 2.17.1
 */
package fr.n7.ui;

import com.google.inject.Injector;
import fr.n7.JEU.ui.internal.JEUActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JEUExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(JEUActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		JEUActivator activator = JEUActivator.getInstance();
		return activator != null ? activator.getInjector(JEUActivator.FR_N7_JEU) : null;
	}

}
