/**
 * generated by Xtext 2.17.1
 */
package fr.n7.ui.contentassist;

import fr.n7.ui.contentassist.AbstractJEUProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class JEUProposalProvider extends AbstractJEUProposalProvider {
}
