/**
 * generated by Xtext 2.17.1
 */
package fr.n7.ide;

import fr.n7.ide.AbstractJEUIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class JEUIdeModule extends AbstractJEUIdeModule {
}
