/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jEU.action#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.jEU.action#getDescription <em>Description</em>}</li>
 *   <li>{@link fr.n7.jEU.action#getAllocateursConnaissance <em>Allocateurs Connaissance</em>}</li>
 *   <li>{@link fr.n7.jEU.action#getAllocateursObjetLieu <em>Allocateurs Objet Lieu</em>}</li>
 *   <li>{@link fr.n7.jEU.action#getConditionAction <em>Condition Action</em>}</li>
 *   <li>{@link fr.n7.jEU.action#getChoixSuivants <em>Choix Suivants</em>}</li>
 *   <li>{@link fr.n7.jEU.action#isEstFinale <em>Est Finale</em>}</li>
 * </ul>
 *
 * @see fr.n7.jEU.JEUPackage#getaction()
 * @model
 * @generated
 */
public interface action extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.jEU.JEUPackage#getaction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.jEU.action#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see fr.n7.jEU.JEUPackage#getaction_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link fr.n7.jEU.action#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Allocateurs Connaissance</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jEU.AllocateurConnaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Allocateurs Connaissance</em>' containment reference list.
   * @see fr.n7.jEU.JEUPackage#getaction_AllocateursConnaissance()
   * @model containment="true"
   * @generated
   */
  EList<AllocateurConnaissance> getAllocateursConnaissance();

  /**
   * Returns the value of the '<em><b>Allocateurs Objet Lieu</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jEU.AllocateurObjet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Allocateurs Objet Lieu</em>' containment reference list.
   * @see fr.n7.jEU.JEUPackage#getaction_AllocateursObjetLieu()
   * @model containment="true"
   * @generated
   */
  EList<AllocateurObjet> getAllocateursObjetLieu();

  /**
   * Returns the value of the '<em><b>Condition Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition Action</em>' containment reference.
   * @see #setConditionAction(condition)
   * @see fr.n7.jEU.JEUPackage#getaction_ConditionAction()
   * @model containment="true"
   * @generated
   */
  condition getConditionAction();

  /**
   * Sets the value of the '{@link fr.n7.jEU.action#getConditionAction <em>Condition Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition Action</em>' containment reference.
   * @see #getConditionAction()
   * @generated
   */
  void setConditionAction(condition value);

  /**
   * Returns the value of the '<em><b>Choix Suivants</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jEU.choix}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choix Suivants</em>' containment reference list.
   * @see fr.n7.jEU.JEUPackage#getaction_ChoixSuivants()
   * @model containment="true"
   * @generated
   */
  EList<choix> getChoixSuivants();

  /**
   * Returns the value of the '<em><b>Est Finale</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Est Finale</em>' attribute.
   * @see #setEstFinale(boolean)
   * @see fr.n7.jEU.JEUPackage#getaction_EstFinale()
   * @model
   * @generated
   */
  boolean isEstFinale();

  /**
   * Sets the value of the '{@link fr.n7.jEU.action#isEstFinale <em>Est Finale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Est Finale</em>' attribute.
   * @see #isEstFinale()
   * @generated
   */
  void setEstFinale(boolean value);

} // action
