/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Allocateur Objet</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jEU.AllocateurObjet#getObjetAlloue <em>Objet Alloue</em>}</li>
 *   <li>{@link fr.n7.jEU.AllocateurObjet#isConsomme <em>Consomme</em>}</li>
 *   <li>{@link fr.n7.jEU.AllocateurObjet#getQuantite <em>Quantite</em>}</li>
 *   <li>{@link fr.n7.jEU.AllocateurObjet#isEstConditionne <em>Est Conditionne</em>}</li>
 *   <li>{@link fr.n7.jEU.AllocateurObjet#getConditionAllocution <em>Condition Allocution</em>}</li>
 * </ul>
 *
 * @see fr.n7.jEU.JEUPackage#getAllocateurObjet()
 * @model
 * @generated
 */
public interface AllocateurObjet extends EObject
{
  /**
   * Returns the value of the '<em><b>Objet Alloue</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objet Alloue</em>' reference.
   * @see #setObjetAlloue(Objet)
   * @see fr.n7.jEU.JEUPackage#getAllocateurObjet_ObjetAlloue()
   * @model
   * @generated
   */
  Objet getObjetAlloue();

  /**
   * Sets the value of the '{@link fr.n7.jEU.AllocateurObjet#getObjetAlloue <em>Objet Alloue</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objet Alloue</em>' reference.
   * @see #getObjetAlloue()
   * @generated
   */
  void setObjetAlloue(Objet value);

  /**
   * Returns the value of the '<em><b>Consomme</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consomme</em>' attribute.
   * @see #setConsomme(boolean)
   * @see fr.n7.jEU.JEUPackage#getAllocateurObjet_Consomme()
   * @model
   * @generated
   */
  boolean isConsomme();

  /**
   * Sets the value of the '{@link fr.n7.jEU.AllocateurObjet#isConsomme <em>Consomme</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Consomme</em>' attribute.
   * @see #isConsomme()
   * @generated
   */
  void setConsomme(boolean value);

  /**
   * Returns the value of the '<em><b>Quantite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantite</em>' attribute.
   * @see #setQuantite(int)
   * @see fr.n7.jEU.JEUPackage#getAllocateurObjet_Quantite()
   * @model
   * @generated
   */
  int getQuantite();

  /**
   * Sets the value of the '{@link fr.n7.jEU.AllocateurObjet#getQuantite <em>Quantite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantite</em>' attribute.
   * @see #getQuantite()
   * @generated
   */
  void setQuantite(int value);

  /**
   * Returns the value of the '<em><b>Est Conditionne</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Est Conditionne</em>' attribute.
   * @see #setEstConditionne(boolean)
   * @see fr.n7.jEU.JEUPackage#getAllocateurObjet_EstConditionne()
   * @model
   * @generated
   */
  boolean isEstConditionne();

  /**
   * Sets the value of the '{@link fr.n7.jEU.AllocateurObjet#isEstConditionne <em>Est Conditionne</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Est Conditionne</em>' attribute.
   * @see #isEstConditionne()
   * @generated
   */
  void setEstConditionne(boolean value);

  /**
   * Returns the value of the '<em><b>Condition Allocution</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition Allocution</em>' containment reference.
   * @see #setConditionAllocution(condition)
   * @see fr.n7.jEU.JEUPackage#getAllocateurObjet_ConditionAllocution()
   * @model containment="true"
   * @generated
   */
  condition getConditionAllocution();

  /**
   * Sets the value of the '{@link fr.n7.jEU.AllocateurObjet#getConditionAllocution <em>Condition Allocution</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition Allocution</em>' containment reference.
   * @see #getConditionAllocution()
   * @generated
   */
  void setConditionAllocution(condition value);

} // AllocateurObjet
