/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chemin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jEU.Chemin#getSource <em>Source</em>}</li>
 *   <li>{@link fr.n7.jEU.Chemin#getDestination <em>Destination</em>}</li>
 *   <li>{@link fr.n7.jEU.Chemin#getOuvertOUferme <em>Ouvert OUferme</em>}</li>
 *   <li>{@link fr.n7.jEU.Chemin#getVisibilite <em>Visibilite</em>}</li>
 *   <li>{@link fr.n7.jEU.Chemin#getAcces <em>Acces</em>}</li>
 *   <li>{@link fr.n7.jEU.Chemin#getVisible <em>Visible</em>}</li>
 *   <li>{@link fr.n7.jEU.Chemin#getAllocateursConnaissance <em>Allocateurs Connaissance</em>}</li>
 *   <li>{@link fr.n7.jEU.Chemin#getAllocateursObjetLieu <em>Allocateurs Objet Lieu</em>}</li>
 * </ul>
 *
 * @see fr.n7.jEU.JEUPackage#getChemin()
 * @model
 * @generated
 */
public interface Chemin extends JeuElement
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(Lieu)
   * @see fr.n7.jEU.JEUPackage#getChemin_Source()
   * @model
   * @generated
   */
  Lieu getSource();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Chemin#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(Lieu value);

  /**
   * Returns the value of the '<em><b>Destination</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destination</em>' reference.
   * @see #setDestination(Lieu)
   * @see fr.n7.jEU.JEUPackage#getChemin_Destination()
   * @model
   * @generated
   */
  Lieu getDestination();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Chemin#getDestination <em>Destination</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Destination</em>' reference.
   * @see #getDestination()
   * @generated
   */
  void setDestination(Lieu value);

  /**
   * Returns the value of the '<em><b>Ouvert OUferme</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.jEU.ouvertOuferme}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ouvert OUferme</em>' attribute.
   * @see fr.n7.jEU.ouvertOuferme
   * @see #setOuvertOUferme(ouvertOuferme)
   * @see fr.n7.jEU.JEUPackage#getChemin_OuvertOUferme()
   * @model
   * @generated
   */
  ouvertOuferme getOuvertOUferme();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Chemin#getOuvertOUferme <em>Ouvert OUferme</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ouvert OUferme</em>' attribute.
   * @see fr.n7.jEU.ouvertOuferme
   * @see #getOuvertOUferme()
   * @generated
   */
  void setOuvertOUferme(ouvertOuferme value);

  /**
   * Returns the value of the '<em><b>Visibilite</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.jEU.typevisibilite}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visibilite</em>' attribute.
   * @see fr.n7.jEU.typevisibilite
   * @see #setVisibilite(typevisibilite)
   * @see fr.n7.jEU.JEUPackage#getChemin_Visibilite()
   * @model
   * @generated
   */
  typevisibilite getVisibilite();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Chemin#getVisibilite <em>Visibilite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visibilite</em>' attribute.
   * @see fr.n7.jEU.typevisibilite
   * @see #getVisibilite()
   * @generated
   */
  void setVisibilite(typevisibilite value);

  /**
   * Returns the value of the '<em><b>Acces</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Acces</em>' containment reference.
   * @see #setAcces(condition)
   * @see fr.n7.jEU.JEUPackage#getChemin_Acces()
   * @model containment="true"
   * @generated
   */
  condition getAcces();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Chemin#getAcces <em>Acces</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Acces</em>' containment reference.
   * @see #getAcces()
   * @generated
   */
  void setAcces(condition value);

  /**
   * Returns the value of the '<em><b>Visible</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible</em>' containment reference.
   * @see #setVisible(condition)
   * @see fr.n7.jEU.JEUPackage#getChemin_Visible()
   * @model containment="true"
   * @generated
   */
  condition getVisible();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Chemin#getVisible <em>Visible</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible</em>' containment reference.
   * @see #getVisible()
   * @generated
   */
  void setVisible(condition value);

  /**
   * Returns the value of the '<em><b>Allocateurs Connaissance</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jEU.AllocateurConnaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Allocateurs Connaissance</em>' containment reference list.
   * @see fr.n7.jEU.JEUPackage#getChemin_AllocateursConnaissance()
   * @model containment="true"
   * @generated
   */
  EList<AllocateurConnaissance> getAllocateursConnaissance();

  /**
   * Returns the value of the '<em><b>Allocateurs Objet Lieu</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jEU.AllocateurObjet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Allocateurs Objet Lieu</em>' containment reference list.
   * @see fr.n7.jEU.JEUPackage#getChemin_AllocateursObjetLieu()
   * @model containment="true"
   * @generated
   */
  EList<AllocateurObjet> getAllocateursObjetLieu();

} // Chemin
