/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>choix</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jEU.choix#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.jEU.choix#getDescription <em>Description</em>}</li>
 *   <li>{@link fr.n7.jEU.choix#getActions <em>Actions</em>}</li>
 *   <li>{@link fr.n7.jEU.choix#isEstFin <em>Est Fin</em>}</li>
 *   <li>{@link fr.n7.jEU.choix#getConditionFin <em>Condition Fin</em>}</li>
 * </ul>
 *
 * @see fr.n7.jEU.JEUPackage#getchoix()
 * @model
 * @generated
 */
public interface choix extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.jEU.JEUPackage#getchoix_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.jEU.choix#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see fr.n7.jEU.JEUPackage#getchoix_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link fr.n7.jEU.choix#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jEU.action}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see fr.n7.jEU.JEUPackage#getchoix_Actions()
   * @model containment="true"
   * @generated
   */
  EList<action> getActions();

  /**
   * Returns the value of the '<em><b>Est Fin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Est Fin</em>' attribute.
   * @see #setEstFin(boolean)
   * @see fr.n7.jEU.JEUPackage#getchoix_EstFin()
   * @model
   * @generated
   */
  boolean isEstFin();

  /**
   * Sets the value of the '{@link fr.n7.jEU.choix#isEstFin <em>Est Fin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Est Fin</em>' attribute.
   * @see #isEstFin()
   * @generated
   */
  void setEstFin(boolean value);

  /**
   * Returns the value of the '<em><b>Condition Fin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition Fin</em>' containment reference.
   * @see #setConditionFin(condition)
   * @see fr.n7.jEU.JEUPackage#getchoix_ConditionFin()
   * @model containment="true"
   * @generated
   */
  condition getConditionFin();

  /**
   * Sets the value of the '{@link fr.n7.jEU.choix#getConditionFin <em>Condition Fin</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition Fin</em>' containment reference.
   * @see #getConditionFin()
   * @generated
   */
  void setConditionFin(condition value);

} // choix
