/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jEU.condition#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.jEU.condition#getObjet <em>Objet</em>}</li>
 *   <li>{@link fr.n7.jEU.condition#getComparaison <em>Comparaison</em>}</li>
 *   <li>{@link fr.n7.jEU.condition#getReference <em>Reference</em>}</li>
 *   <li>{@link fr.n7.jEU.condition#getConnaissance <em>Connaissance</em>}</li>
 *   <li>{@link fr.n7.jEU.condition#isPresente <em>Presente</em>}</li>
 * </ul>
 *
 * @see fr.n7.jEU.JEUPackage#getcondition()
 * @model
 * @generated
 */
public interface condition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.jEU.JEUPackage#getcondition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.jEU.condition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Objet</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objet</em>' reference.
   * @see #setObjet(Objet)
   * @see fr.n7.jEU.JEUPackage#getcondition_Objet()
   * @model
   * @generated
   */
  Objet getObjet();

  /**
   * Sets the value of the '{@link fr.n7.jEU.condition#getObjet <em>Objet</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objet</em>' reference.
   * @see #getObjet()
   * @generated
   */
  void setObjet(Objet value);

  /**
   * Returns the value of the '<em><b>Comparaison</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.jEU.Comparateur}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparaison</em>' attribute.
   * @see fr.n7.jEU.Comparateur
   * @see #setComparaison(Comparateur)
   * @see fr.n7.jEU.JEUPackage#getcondition_Comparaison()
   * @model
   * @generated
   */
  Comparateur getComparaison();

  /**
   * Sets the value of the '{@link fr.n7.jEU.condition#getComparaison <em>Comparaison</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparaison</em>' attribute.
   * @see fr.n7.jEU.Comparateur
   * @see #getComparaison()
   * @generated
   */
  void setComparaison(Comparateur value);

  /**
   * Returns the value of the '<em><b>Reference</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference</em>' attribute.
   * @see #setReference(int)
   * @see fr.n7.jEU.JEUPackage#getcondition_Reference()
   * @model
   * @generated
   */
  int getReference();

  /**
   * Sets the value of the '{@link fr.n7.jEU.condition#getReference <em>Reference</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference</em>' attribute.
   * @see #getReference()
   * @generated
   */
  void setReference(int value);

  /**
   * Returns the value of the '<em><b>Connaissance</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connaissance</em>' reference.
   * @see #setConnaissance(Connaissance)
   * @see fr.n7.jEU.JEUPackage#getcondition_Connaissance()
   * @model
   * @generated
   */
  Connaissance getConnaissance();

  /**
   * Sets the value of the '{@link fr.n7.jEU.condition#getConnaissance <em>Connaissance</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Connaissance</em>' reference.
   * @see #getConnaissance()
   * @generated
   */
  void setConnaissance(Connaissance value);

  /**
   * Returns the value of the '<em><b>Presente</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Presente</em>' attribute.
   * @see #setPresente(boolean)
   * @see fr.n7.jEU.JEUPackage#getcondition_Presente()
   * @model
   * @generated
   */
  boolean isPresente();

  /**
   * Sets the value of the '{@link fr.n7.jEU.condition#isPresente <em>Presente</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Presente</em>' attribute.
   * @see #isPresente()
   * @generated
   */
  void setPresente(boolean value);

} // condition
