/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connaissance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jEU.Connaissance#getVisibilite <em>Visibilite</em>}</li>
 *   <li>{@link fr.n7.jEU.Connaissance#getActivite <em>Activite</em>}</li>
 *   <li>{@link fr.n7.jEU.Connaissance#isEstPossede <em>Est Possede</em>}</li>
 *   <li>{@link fr.n7.jEU.Connaissance#getAcces <em>Acces</em>}</li>
 *   <li>{@link fr.n7.jEU.Connaissance#getVisible <em>Visible</em>}</li>
 * </ul>
 *
 * @see fr.n7.jEU.JEUPackage#getConnaissance()
 * @model
 * @generated
 */
public interface Connaissance extends JeuElement
{
  /**
   * Returns the value of the '<em><b>Visibilite</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.jEU.typevisibilite}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visibilite</em>' attribute.
   * @see fr.n7.jEU.typevisibilite
   * @see #setVisibilite(typevisibilite)
   * @see fr.n7.jEU.JEUPackage#getConnaissance_Visibilite()
   * @model
   * @generated
   */
  typevisibilite getVisibilite();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Connaissance#getVisibilite <em>Visibilite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visibilite</em>' attribute.
   * @see fr.n7.jEU.typevisibilite
   * @see #getVisibilite()
   * @generated
   */
  void setVisibilite(typevisibilite value);

  /**
   * Returns the value of the '<em><b>Activite</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.jEU.typeactivite}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activite</em>' attribute.
   * @see fr.n7.jEU.typeactivite
   * @see #setActivite(typeactivite)
   * @see fr.n7.jEU.JEUPackage#getConnaissance_Activite()
   * @model
   * @generated
   */
  typeactivite getActivite();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Connaissance#getActivite <em>Activite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Activite</em>' attribute.
   * @see fr.n7.jEU.typeactivite
   * @see #getActivite()
   * @generated
   */
  void setActivite(typeactivite value);

  /**
   * Returns the value of the '<em><b>Est Possede</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Est Possede</em>' attribute.
   * @see #setEstPossede(boolean)
   * @see fr.n7.jEU.JEUPackage#getConnaissance_EstPossede()
   * @model
   * @generated
   */
  boolean isEstPossede();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Connaissance#isEstPossede <em>Est Possede</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Est Possede</em>' attribute.
   * @see #isEstPossede()
   * @generated
   */
  void setEstPossede(boolean value);

  /**
   * Returns the value of the '<em><b>Acces</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Acces</em>' containment reference.
   * @see #setAcces(condition)
   * @see fr.n7.jEU.JEUPackage#getConnaissance_Acces()
   * @model containment="true"
   * @generated
   */
  condition getAcces();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Connaissance#getAcces <em>Acces</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Acces</em>' containment reference.
   * @see #getAcces()
   * @generated
   */
  void setAcces(condition value);

  /**
   * Returns the value of the '<em><b>Visible</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible</em>' containment reference.
   * @see #setVisible(condition)
   * @see fr.n7.jEU.JEUPackage#getConnaissance_Visible()
   * @model containment="true"
   * @generated
   */
  condition getVisible();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Connaissance#getVisible <em>Visible</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible</em>' containment reference.
   * @see #getVisible()
   * @generated
   */
  void setVisible(condition value);

} // Connaissance
