/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jEU.Interaction#getPersonne <em>Personne</em>}</li>
 *   <li>{@link fr.n7.jEU.Interaction#getQuestion <em>Question</em>}</li>
 *   <li>{@link fr.n7.jEU.Interaction#getChoix <em>Choix</em>}</li>
 *   <li>{@link fr.n7.jEU.Interaction#getChoixJoueur <em>Choix Joueur</em>}</li>
 * </ul>
 *
 * @see fr.n7.jEU.JEUPackage#getInteraction()
 * @model
 * @generated
 */
public interface Interaction extends EObject
{
  /**
   * Returns the value of the '<em><b>Personne</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Personne</em>' reference.
   * @see #setPersonne(Personne)
   * @see fr.n7.jEU.JEUPackage#getInteraction_Personne()
   * @model
   * @generated
   */
  Personne getPersonne();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Interaction#getPersonne <em>Personne</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Personne</em>' reference.
   * @see #getPersonne()
   * @generated
   */
  void setPersonne(Personne value);

  /**
   * Returns the value of the '<em><b>Question</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Question</em>' attribute.
   * @see #setQuestion(String)
   * @see fr.n7.jEU.JEUPackage#getInteraction_Question()
   * @model
   * @generated
   */
  String getQuestion();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Interaction#getQuestion <em>Question</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Question</em>' attribute.
   * @see #getQuestion()
   * @generated
   */
  void setQuestion(String value);

  /**
   * Returns the value of the '<em><b>Choix</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jEU.choix}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choix</em>' containment reference list.
   * @see fr.n7.jEU.JEUPackage#getInteraction_Choix()
   * @model containment="true"
   * @generated
   */
  EList<choix> getChoix();

  /**
   * Returns the value of the '<em><b>Choix Joueur</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jEU.choix}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choix Joueur</em>' containment reference list.
   * @see fr.n7.jEU.JEUPackage#getInteraction_ChoixJoueur()
   * @model containment="true"
   * @generated
   */
  EList<choix> getChoixJoueur();

} // Interaction
