/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.n7.jEU.JEUFactory
 * @model kind="package"
 * @generated
 */
public interface JEUPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "jEU";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.n7.fr/JEU";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "jEU";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JEUPackage eINSTANCE = fr.n7.jEU.impl.JEUPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.n7.jEU.impl.JeuImpl <em>Jeu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.impl.JeuImpl
   * @see fr.n7.jEU.impl.JEUPackageImpl#getJeu()
   * @generated
   */
  int JEU = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__NAME = 0;

  /**
   * The feature id for the '<em><b>Joueur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__JOUEUR = 1;

  /**
   * The feature id for the '<em><b>Jeuelement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__JEUELEMENT = 2;

  /**
   * The number of structural features of the '<em>Jeu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.n7.jEU.impl.JeuElementImpl <em>Jeu Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.impl.JeuElementImpl
   * @see fr.n7.jEU.impl.JEUPackageImpl#getJeuElement()
   * @generated
   */
  int JEU_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU_ELEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU_ELEMENT__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Jeu Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU_ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.jEU.impl.JoueurImpl <em>Joueur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.impl.JoueurImpl
   * @see fr.n7.jEU.impl.JEUPackageImpl#getJoueur()
   * @generated
   */
  int JOUEUR = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOUEUR__NAME = 0;

  /**
   * The feature id for the '<em><b>Connaissance</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOUEUR__CONNAISSANCE = 1;

  /**
   * The feature id for the '<em><b>Tailleinventaire</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOUEUR__TAILLEINVENTAIRE = 2;

  /**
   * The feature id for the '<em><b>Objets</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOUEUR__OBJETS = 3;

  /**
   * The feature id for the '<em><b>Lieu</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOUEUR__LIEU = 4;

  /**
   * The number of structural features of the '<em>Joueur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOUEUR_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.n7.jEU.impl.CheminImpl <em>Chemin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.impl.CheminImpl
   * @see fr.n7.jEU.impl.JEUPackageImpl#getChemin()
   * @generated
   */
  int CHEMIN = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__NAME = JEU_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__DESCRIPTION = JEU_ELEMENT__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__SOURCE = JEU_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Destination</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__DESTINATION = JEU_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Ouvert OUferme</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__OUVERT_OUFERME = JEU_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Visibilite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__VISIBILITE = JEU_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Acces</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__ACCES = JEU_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Visible</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__VISIBLE = JEU_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Allocateurs Connaissance</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__ALLOCATEURS_CONNAISSANCE = JEU_ELEMENT_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Allocateurs Objet Lieu</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__ALLOCATEURS_OBJET_LIEU = JEU_ELEMENT_FEATURE_COUNT + 7;

  /**
   * The number of structural features of the '<em>Chemin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN_FEATURE_COUNT = JEU_ELEMENT_FEATURE_COUNT + 8;

  /**
   * The meta object id for the '{@link fr.n7.jEU.impl.AllocateurConnaissanceImpl <em>Allocateur Connaissance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.impl.AllocateurConnaissanceImpl
   * @see fr.n7.jEU.impl.JEUPackageImpl#getAllocateurConnaissance()
   * @generated
   */
  int ALLOCATEUR_CONNAISSANCE = 4;

  /**
   * The feature id for the '<em><b>Connaissance Alloue</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOCATEUR_CONNAISSANCE__CONNAISSANCE_ALLOUE = 0;

  /**
   * The feature id for the '<em><b>Est Conditionne</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOCATEUR_CONNAISSANCE__EST_CONDITIONNE = 1;

  /**
   * The feature id for the '<em><b>Condition Allocution</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOCATEUR_CONNAISSANCE__CONDITION_ALLOCUTION = 2;

  /**
   * The number of structural features of the '<em>Allocateur Connaissance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOCATEUR_CONNAISSANCE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.n7.jEU.impl.AllocateurObjetImpl <em>Allocateur Objet</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.impl.AllocateurObjetImpl
   * @see fr.n7.jEU.impl.JEUPackageImpl#getAllocateurObjet()
   * @generated
   */
  int ALLOCATEUR_OBJET = 5;

  /**
   * The feature id for the '<em><b>Objet Alloue</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOCATEUR_OBJET__OBJET_ALLOUE = 0;

  /**
   * The feature id for the '<em><b>Consomme</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOCATEUR_OBJET__CONSOMME = 1;

  /**
   * The feature id for the '<em><b>Quantite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOCATEUR_OBJET__QUANTITE = 2;

  /**
   * The feature id for the '<em><b>Est Conditionne</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOCATEUR_OBJET__EST_CONDITIONNE = 3;

  /**
   * The feature id for the '<em><b>Condition Allocution</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOCATEUR_OBJET__CONDITION_ALLOCUTION = 4;

  /**
   * The number of structural features of the '<em>Allocateur Objet</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOCATEUR_OBJET_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.n7.jEU.impl.LieuImpl <em>Lieu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.impl.LieuImpl
   * @see fr.n7.jEU.impl.JEUPackageImpl#getLieu()
   * @generated
   */
  int LIEU = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__NAME = JEU_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__DESCRIPTION = JEU_ELEMENT__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__TYPE = JEU_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Connaissance</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__CONNAISSANCE = JEU_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Objetslieu</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__OBJETSLIEU = JEU_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Personnes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__PERSONNES = JEU_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Lieu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FEATURE_COUNT = JEU_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link fr.n7.jEU.impl.ConnaissanceImpl <em>Connaissance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.impl.ConnaissanceImpl
   * @see fr.n7.jEU.impl.JEUPackageImpl#getConnaissance()
   * @generated
   */
  int CONNAISSANCE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__NAME = JEU_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__DESCRIPTION = JEU_ELEMENT__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Visibilite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__VISIBILITE = JEU_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Activite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__ACTIVITE = JEU_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Est Possede</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__EST_POSSEDE = JEU_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Acces</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__ACCES = JEU_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Visible</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__VISIBLE = JEU_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Connaissance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE_FEATURE_COUNT = JEU_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link fr.n7.jEU.impl.ObjetImpl <em>Objet</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.impl.ObjetImpl
   * @see fr.n7.jEU.impl.JEUPackageImpl#getObjet()
   * @generated
   */
  int OBJET = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__NAME = JEU_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__DESCRIPTION = JEU_ELEMENT__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Taille</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__TAILLE = JEU_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Quantite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__QUANTITE = JEU_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Visibilite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__VISIBILITE = JEU_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Activite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__ACTIVITE = JEU_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Dans Lieu</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__DANS_LIEU = JEU_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Lieu</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__LIEU = JEU_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Condition Deposer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__CONDITION_DEPOSER = JEU_ELEMENT_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>Objet</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_FEATURE_COUNT = JEU_ELEMENT_FEATURE_COUNT + 7;

  /**
   * The meta object id for the '{@link fr.n7.jEU.impl.InteractionImpl <em>Interaction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.impl.InteractionImpl
   * @see fr.n7.jEU.impl.JEUPackageImpl#getInteraction()
   * @generated
   */
  int INTERACTION = 9;

  /**
   * The feature id for the '<em><b>Personne</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__PERSONNE = 0;

  /**
   * The feature id for the '<em><b>Question</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__QUESTION = 1;

  /**
   * The feature id for the '<em><b>Choix</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__CHOIX = 2;

  /**
   * The feature id for the '<em><b>Choix Joueur</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__CHOIX_JOUEUR = 3;

  /**
   * The number of structural features of the '<em>Interaction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.n7.jEU.impl.conditionImpl <em>condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.impl.conditionImpl
   * @see fr.n7.jEU.impl.JEUPackageImpl#getcondition()
   * @generated
   */
  int CONDITION = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Objet</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__OBJET = 1;

  /**
   * The feature id for the '<em><b>Comparaison</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__COMPARAISON = 2;

  /**
   * The feature id for the '<em><b>Reference</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__REFERENCE = 3;

  /**
   * The feature id for the '<em><b>Connaissance</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__CONNAISSANCE = 4;

  /**
   * The feature id for the '<em><b>Presente</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__PRESENTE = 5;

  /**
   * The number of structural features of the '<em>condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link fr.n7.jEU.impl.PersonneImpl <em>Personne</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.impl.PersonneImpl
   * @see fr.n7.jEU.impl.JEUPackageImpl#getPersonne()
   * @generated
   */
  int PERSONNE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__NAME = 0;

  /**
   * The feature id for the '<em><b>Visibilite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__VISIBILITE = 1;

  /**
   * The feature id for the '<em><b>Activite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__ACTIVITE = 2;

  /**
   * The feature id for the '<em><b>Interaction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__INTERACTION = 3;

  /**
   * The number of structural features of the '<em>Personne</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.n7.jEU.impl.choixImpl <em>choix</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.impl.choixImpl
   * @see fr.n7.jEU.impl.JEUPackageImpl#getchoix()
   * @generated
   */
  int CHOIX = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__ACTIONS = 2;

  /**
   * The feature id for the '<em><b>Est Fin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__EST_FIN = 3;

  /**
   * The feature id for the '<em><b>Condition Fin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__CONDITION_FIN = 4;

  /**
   * The number of structural features of the '<em>choix</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.n7.jEU.impl.actionImpl <em>action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.impl.actionImpl
   * @see fr.n7.jEU.impl.JEUPackageImpl#getaction()
   * @generated
   */
  int ACTION = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Allocateurs Connaissance</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ALLOCATEURS_CONNAISSANCE = 2;

  /**
   * The feature id for the '<em><b>Allocateurs Objet Lieu</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ALLOCATEURS_OBJET_LIEU = 3;

  /**
   * The feature id for the '<em><b>Condition Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__CONDITION_ACTION = 4;

  /**
   * The feature id for the '<em><b>Choix Suivants</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__CHOIX_SUIVANTS = 5;

  /**
   * The feature id for the '<em><b>Est Finale</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__EST_FINALE = 6;

  /**
   * The number of structural features of the '<em>action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link fr.n7.jEU.Comparateur <em>Comparateur</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.Comparateur
   * @see fr.n7.jEU.impl.JEUPackageImpl#getComparateur()
   * @generated
   */
  int COMPARATEUR = 14;

  /**
   * The meta object id for the '{@link fr.n7.jEU.typevisibilite <em>typevisibilite</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.typevisibilite
   * @see fr.n7.jEU.impl.JEUPackageImpl#gettypevisibilite()
   * @generated
   */
  int TYPEVISIBILITE = 15;

  /**
   * The meta object id for the '{@link fr.n7.jEU.typeLieu <em>type Lieu</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.typeLieu
   * @see fr.n7.jEU.impl.JEUPackageImpl#gettypeLieu()
   * @generated
   */
  int TYPE_LIEU = 16;

  /**
   * The meta object id for the '{@link fr.n7.jEU.ouvertOuferme <em>ouvert Ouferme</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.ouvertOuferme
   * @see fr.n7.jEU.impl.JEUPackageImpl#getouvertOuferme()
   * @generated
   */
  int OUVERT_OUFERME = 17;

  /**
   * The meta object id for the '{@link fr.n7.jEU.typeactivite <em>typeactivite</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.jEU.typeactivite
   * @see fr.n7.jEU.impl.JEUPackageImpl#gettypeactivite()
   * @generated
   */
  int TYPEACTIVITE = 18;


  /**
   * Returns the meta object for class '{@link fr.n7.jEU.Jeu <em>Jeu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Jeu</em>'.
   * @see fr.n7.jEU.Jeu
   * @generated
   */
  EClass getJeu();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Jeu#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.jEU.Jeu#getName()
   * @see #getJeu()
   * @generated
   */
  EAttribute getJeu_Name();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.jEU.Jeu#getJoueur <em>Joueur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Joueur</em>'.
   * @see fr.n7.jEU.Jeu#getJoueur()
   * @see #getJeu()
   * @generated
   */
  EReference getJeu_Joueur();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jEU.Jeu#getJeuelement <em>Jeuelement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Jeuelement</em>'.
   * @see fr.n7.jEU.Jeu#getJeuelement()
   * @see #getJeu()
   * @generated
   */
  EReference getJeu_Jeuelement();

  /**
   * Returns the meta object for class '{@link fr.n7.jEU.JeuElement <em>Jeu Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Jeu Element</em>'.
   * @see fr.n7.jEU.JeuElement
   * @generated
   */
  EClass getJeuElement();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.JeuElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.jEU.JeuElement#getName()
   * @see #getJeuElement()
   * @generated
   */
  EAttribute getJeuElement_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.JeuElement#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see fr.n7.jEU.JeuElement#getDescription()
   * @see #getJeuElement()
   * @generated
   */
  EAttribute getJeuElement_Description();

  /**
   * Returns the meta object for class '{@link fr.n7.jEU.Joueur <em>Joueur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Joueur</em>'.
   * @see fr.n7.jEU.Joueur
   * @generated
   */
  EClass getJoueur();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Joueur#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.jEU.Joueur#getName()
   * @see #getJoueur()
   * @generated
   */
  EAttribute getJoueur_Name();

  /**
   * Returns the meta object for the reference list '{@link fr.n7.jEU.Joueur#getConnaissance <em>Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Connaissance</em>'.
   * @see fr.n7.jEU.Joueur#getConnaissance()
   * @see #getJoueur()
   * @generated
   */
  EReference getJoueur_Connaissance();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Joueur#getTailleinventaire <em>Tailleinventaire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tailleinventaire</em>'.
   * @see fr.n7.jEU.Joueur#getTailleinventaire()
   * @see #getJoueur()
   * @generated
   */
  EAttribute getJoueur_Tailleinventaire();

  /**
   * Returns the meta object for the reference list '{@link fr.n7.jEU.Joueur#getObjets <em>Objets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Objets</em>'.
   * @see fr.n7.jEU.Joueur#getObjets()
   * @see #getJoueur()
   * @generated
   */
  EReference getJoueur_Objets();

  /**
   * Returns the meta object for the reference '{@link fr.n7.jEU.Joueur#getLieu <em>Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Lieu</em>'.
   * @see fr.n7.jEU.Joueur#getLieu()
   * @see #getJoueur()
   * @generated
   */
  EReference getJoueur_Lieu();

  /**
   * Returns the meta object for class '{@link fr.n7.jEU.Chemin <em>Chemin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chemin</em>'.
   * @see fr.n7.jEU.Chemin
   * @generated
   */
  EClass getChemin();

  /**
   * Returns the meta object for the reference '{@link fr.n7.jEU.Chemin#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source</em>'.
   * @see fr.n7.jEU.Chemin#getSource()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Source();

  /**
   * Returns the meta object for the reference '{@link fr.n7.jEU.Chemin#getDestination <em>Destination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Destination</em>'.
   * @see fr.n7.jEU.Chemin#getDestination()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Destination();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Chemin#getOuvertOUferme <em>Ouvert OUferme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ouvert OUferme</em>'.
   * @see fr.n7.jEU.Chemin#getOuvertOUferme()
   * @see #getChemin()
   * @generated
   */
  EAttribute getChemin_OuvertOUferme();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Chemin#getVisibilite <em>Visibilite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibilite</em>'.
   * @see fr.n7.jEU.Chemin#getVisibilite()
   * @see #getChemin()
   * @generated
   */
  EAttribute getChemin_Visibilite();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.jEU.Chemin#getAcces <em>Acces</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Acces</em>'.
   * @see fr.n7.jEU.Chemin#getAcces()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Acces();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.jEU.Chemin#getVisible <em>Visible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Visible</em>'.
   * @see fr.n7.jEU.Chemin#getVisible()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Visible();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jEU.Chemin#getAllocateursConnaissance <em>Allocateurs Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Allocateurs Connaissance</em>'.
   * @see fr.n7.jEU.Chemin#getAllocateursConnaissance()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_AllocateursConnaissance();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jEU.Chemin#getAllocateursObjetLieu <em>Allocateurs Objet Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Allocateurs Objet Lieu</em>'.
   * @see fr.n7.jEU.Chemin#getAllocateursObjetLieu()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_AllocateursObjetLieu();

  /**
   * Returns the meta object for class '{@link fr.n7.jEU.AllocateurConnaissance <em>Allocateur Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Allocateur Connaissance</em>'.
   * @see fr.n7.jEU.AllocateurConnaissance
   * @generated
   */
  EClass getAllocateurConnaissance();

  /**
   * Returns the meta object for the reference '{@link fr.n7.jEU.AllocateurConnaissance#getConnaissanceAlloue <em>Connaissance Alloue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Connaissance Alloue</em>'.
   * @see fr.n7.jEU.AllocateurConnaissance#getConnaissanceAlloue()
   * @see #getAllocateurConnaissance()
   * @generated
   */
  EReference getAllocateurConnaissance_ConnaissanceAlloue();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.AllocateurConnaissance#isEstConditionne <em>Est Conditionne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Est Conditionne</em>'.
   * @see fr.n7.jEU.AllocateurConnaissance#isEstConditionne()
   * @see #getAllocateurConnaissance()
   * @generated
   */
  EAttribute getAllocateurConnaissance_EstConditionne();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.jEU.AllocateurConnaissance#getConditionAllocution <em>Condition Allocution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Allocution</em>'.
   * @see fr.n7.jEU.AllocateurConnaissance#getConditionAllocution()
   * @see #getAllocateurConnaissance()
   * @generated
   */
  EReference getAllocateurConnaissance_ConditionAllocution();

  /**
   * Returns the meta object for class '{@link fr.n7.jEU.AllocateurObjet <em>Allocateur Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Allocateur Objet</em>'.
   * @see fr.n7.jEU.AllocateurObjet
   * @generated
   */
  EClass getAllocateurObjet();

  /**
   * Returns the meta object for the reference '{@link fr.n7.jEU.AllocateurObjet#getObjetAlloue <em>Objet Alloue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Objet Alloue</em>'.
   * @see fr.n7.jEU.AllocateurObjet#getObjetAlloue()
   * @see #getAllocateurObjet()
   * @generated
   */
  EReference getAllocateurObjet_ObjetAlloue();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.AllocateurObjet#isConsomme <em>Consomme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Consomme</em>'.
   * @see fr.n7.jEU.AllocateurObjet#isConsomme()
   * @see #getAllocateurObjet()
   * @generated
   */
  EAttribute getAllocateurObjet_Consomme();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.AllocateurObjet#getQuantite <em>Quantite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantite</em>'.
   * @see fr.n7.jEU.AllocateurObjet#getQuantite()
   * @see #getAllocateurObjet()
   * @generated
   */
  EAttribute getAllocateurObjet_Quantite();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.AllocateurObjet#isEstConditionne <em>Est Conditionne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Est Conditionne</em>'.
   * @see fr.n7.jEU.AllocateurObjet#isEstConditionne()
   * @see #getAllocateurObjet()
   * @generated
   */
  EAttribute getAllocateurObjet_EstConditionne();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.jEU.AllocateurObjet#getConditionAllocution <em>Condition Allocution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Allocution</em>'.
   * @see fr.n7.jEU.AllocateurObjet#getConditionAllocution()
   * @see #getAllocateurObjet()
   * @generated
   */
  EReference getAllocateurObjet_ConditionAllocution();

  /**
   * Returns the meta object for class '{@link fr.n7.jEU.Lieu <em>Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lieu</em>'.
   * @see fr.n7.jEU.Lieu
   * @generated
   */
  EClass getLieu();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Lieu#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see fr.n7.jEU.Lieu#getType()
   * @see #getLieu()
   * @generated
   */
  EAttribute getLieu_Type();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jEU.Lieu#getConnaissance <em>Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Connaissance</em>'.
   * @see fr.n7.jEU.Lieu#getConnaissance()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_Connaissance();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jEU.Lieu#getObjetslieu <em>Objetslieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Objetslieu</em>'.
   * @see fr.n7.jEU.Lieu#getObjetslieu()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_Objetslieu();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jEU.Lieu#getPersonnes <em>Personnes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Personnes</em>'.
   * @see fr.n7.jEU.Lieu#getPersonnes()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_Personnes();

  /**
   * Returns the meta object for class '{@link fr.n7.jEU.Connaissance <em>Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connaissance</em>'.
   * @see fr.n7.jEU.Connaissance
   * @generated
   */
  EClass getConnaissance();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Connaissance#getVisibilite <em>Visibilite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibilite</em>'.
   * @see fr.n7.jEU.Connaissance#getVisibilite()
   * @see #getConnaissance()
   * @generated
   */
  EAttribute getConnaissance_Visibilite();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Connaissance#getActivite <em>Activite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Activite</em>'.
   * @see fr.n7.jEU.Connaissance#getActivite()
   * @see #getConnaissance()
   * @generated
   */
  EAttribute getConnaissance_Activite();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Connaissance#isEstPossede <em>Est Possede</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Est Possede</em>'.
   * @see fr.n7.jEU.Connaissance#isEstPossede()
   * @see #getConnaissance()
   * @generated
   */
  EAttribute getConnaissance_EstPossede();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.jEU.Connaissance#getAcces <em>Acces</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Acces</em>'.
   * @see fr.n7.jEU.Connaissance#getAcces()
   * @see #getConnaissance()
   * @generated
   */
  EReference getConnaissance_Acces();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.jEU.Connaissance#getVisible <em>Visible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Visible</em>'.
   * @see fr.n7.jEU.Connaissance#getVisible()
   * @see #getConnaissance()
   * @generated
   */
  EReference getConnaissance_Visible();

  /**
   * Returns the meta object for class '{@link fr.n7.jEU.Objet <em>Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Objet</em>'.
   * @see fr.n7.jEU.Objet
   * @generated
   */
  EClass getObjet();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Objet#getTaille <em>Taille</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Taille</em>'.
   * @see fr.n7.jEU.Objet#getTaille()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_Taille();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Objet#getQuantite <em>Quantite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantite</em>'.
   * @see fr.n7.jEU.Objet#getQuantite()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_Quantite();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Objet#getVisibilite <em>Visibilite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibilite</em>'.
   * @see fr.n7.jEU.Objet#getVisibilite()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_Visibilite();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Objet#getActivite <em>Activite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Activite</em>'.
   * @see fr.n7.jEU.Objet#getActivite()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_Activite();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Objet#isDansLieu <em>Dans Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dans Lieu</em>'.
   * @see fr.n7.jEU.Objet#isDansLieu()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_DansLieu();

  /**
   * Returns the meta object for the reference '{@link fr.n7.jEU.Objet#getLieu <em>Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Lieu</em>'.
   * @see fr.n7.jEU.Objet#getLieu()
   * @see #getObjet()
   * @generated
   */
  EReference getObjet_Lieu();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.jEU.Objet#getConditionDeposer <em>Condition Deposer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Deposer</em>'.
   * @see fr.n7.jEU.Objet#getConditionDeposer()
   * @see #getObjet()
   * @generated
   */
  EReference getObjet_ConditionDeposer();

  /**
   * Returns the meta object for class '{@link fr.n7.jEU.Interaction <em>Interaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interaction</em>'.
   * @see fr.n7.jEU.Interaction
   * @generated
   */
  EClass getInteraction();

  /**
   * Returns the meta object for the reference '{@link fr.n7.jEU.Interaction#getPersonne <em>Personne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Personne</em>'.
   * @see fr.n7.jEU.Interaction#getPersonne()
   * @see #getInteraction()
   * @generated
   */
  EReference getInteraction_Personne();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Interaction#getQuestion <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Question</em>'.
   * @see fr.n7.jEU.Interaction#getQuestion()
   * @see #getInteraction()
   * @generated
   */
  EAttribute getInteraction_Question();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jEU.Interaction#getChoix <em>Choix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Choix</em>'.
   * @see fr.n7.jEU.Interaction#getChoix()
   * @see #getInteraction()
   * @generated
   */
  EReference getInteraction_Choix();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jEU.Interaction#getChoixJoueur <em>Choix Joueur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Choix Joueur</em>'.
   * @see fr.n7.jEU.Interaction#getChoixJoueur()
   * @see #getInteraction()
   * @generated
   */
  EReference getInteraction_ChoixJoueur();

  /**
   * Returns the meta object for class '{@link fr.n7.jEU.condition <em>condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>condition</em>'.
   * @see fr.n7.jEU.condition
   * @generated
   */
  EClass getcondition();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.condition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.jEU.condition#getName()
   * @see #getcondition()
   * @generated
   */
  EAttribute getcondition_Name();

  /**
   * Returns the meta object for the reference '{@link fr.n7.jEU.condition#getObjet <em>Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Objet</em>'.
   * @see fr.n7.jEU.condition#getObjet()
   * @see #getcondition()
   * @generated
   */
  EReference getcondition_Objet();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.condition#getComparaison <em>Comparaison</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparaison</em>'.
   * @see fr.n7.jEU.condition#getComparaison()
   * @see #getcondition()
   * @generated
   */
  EAttribute getcondition_Comparaison();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.condition#getReference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Reference</em>'.
   * @see fr.n7.jEU.condition#getReference()
   * @see #getcondition()
   * @generated
   */
  EAttribute getcondition_Reference();

  /**
   * Returns the meta object for the reference '{@link fr.n7.jEU.condition#getConnaissance <em>Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Connaissance</em>'.
   * @see fr.n7.jEU.condition#getConnaissance()
   * @see #getcondition()
   * @generated
   */
  EReference getcondition_Connaissance();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.condition#isPresente <em>Presente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Presente</em>'.
   * @see fr.n7.jEU.condition#isPresente()
   * @see #getcondition()
   * @generated
   */
  EAttribute getcondition_Presente();

  /**
   * Returns the meta object for class '{@link fr.n7.jEU.Personne <em>Personne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Personne</em>'.
   * @see fr.n7.jEU.Personne
   * @generated
   */
  EClass getPersonne();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Personne#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.jEU.Personne#getName()
   * @see #getPersonne()
   * @generated
   */
  EAttribute getPersonne_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Personne#getVisibilite <em>Visibilite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibilite</em>'.
   * @see fr.n7.jEU.Personne#getVisibilite()
   * @see #getPersonne()
   * @generated
   */
  EAttribute getPersonne_Visibilite();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.Personne#getActivite <em>Activite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Activite</em>'.
   * @see fr.n7.jEU.Personne#getActivite()
   * @see #getPersonne()
   * @generated
   */
  EAttribute getPersonne_Activite();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.jEU.Personne#getInteraction <em>Interaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Interaction</em>'.
   * @see fr.n7.jEU.Personne#getInteraction()
   * @see #getPersonne()
   * @generated
   */
  EReference getPersonne_Interaction();

  /**
   * Returns the meta object for class '{@link fr.n7.jEU.choix <em>choix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>choix</em>'.
   * @see fr.n7.jEU.choix
   * @generated
   */
  EClass getchoix();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.choix#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.jEU.choix#getName()
   * @see #getchoix()
   * @generated
   */
  EAttribute getchoix_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.choix#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see fr.n7.jEU.choix#getDescription()
   * @see #getchoix()
   * @generated
   */
  EAttribute getchoix_Description();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jEU.choix#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see fr.n7.jEU.choix#getActions()
   * @see #getchoix()
   * @generated
   */
  EReference getchoix_Actions();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.choix#isEstFin <em>Est Fin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Est Fin</em>'.
   * @see fr.n7.jEU.choix#isEstFin()
   * @see #getchoix()
   * @generated
   */
  EAttribute getchoix_EstFin();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.jEU.choix#getConditionFin <em>Condition Fin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Fin</em>'.
   * @see fr.n7.jEU.choix#getConditionFin()
   * @see #getchoix()
   * @generated
   */
  EReference getchoix_ConditionFin();

  /**
   * Returns the meta object for class '{@link fr.n7.jEU.action <em>action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>action</em>'.
   * @see fr.n7.jEU.action
   * @generated
   */
  EClass getaction();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.action#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.jEU.action#getName()
   * @see #getaction()
   * @generated
   */
  EAttribute getaction_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.action#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see fr.n7.jEU.action#getDescription()
   * @see #getaction()
   * @generated
   */
  EAttribute getaction_Description();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jEU.action#getAllocateursConnaissance <em>Allocateurs Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Allocateurs Connaissance</em>'.
   * @see fr.n7.jEU.action#getAllocateursConnaissance()
   * @see #getaction()
   * @generated
   */
  EReference getaction_AllocateursConnaissance();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jEU.action#getAllocateursObjetLieu <em>Allocateurs Objet Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Allocateurs Objet Lieu</em>'.
   * @see fr.n7.jEU.action#getAllocateursObjetLieu()
   * @see #getaction()
   * @generated
   */
  EReference getaction_AllocateursObjetLieu();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.jEU.action#getConditionAction <em>Condition Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Action</em>'.
   * @see fr.n7.jEU.action#getConditionAction()
   * @see #getaction()
   * @generated
   */
  EReference getaction_ConditionAction();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.jEU.action#getChoixSuivants <em>Choix Suivants</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Choix Suivants</em>'.
   * @see fr.n7.jEU.action#getChoixSuivants()
   * @see #getaction()
   * @generated
   */
  EReference getaction_ChoixSuivants();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.jEU.action#isEstFinale <em>Est Finale</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Est Finale</em>'.
   * @see fr.n7.jEU.action#isEstFinale()
   * @see #getaction()
   * @generated
   */
  EAttribute getaction_EstFinale();

  /**
   * Returns the meta object for enum '{@link fr.n7.jEU.Comparateur <em>Comparateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Comparateur</em>'.
   * @see fr.n7.jEU.Comparateur
   * @generated
   */
  EEnum getComparateur();

  /**
   * Returns the meta object for enum '{@link fr.n7.jEU.typevisibilite <em>typevisibilite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>typevisibilite</em>'.
   * @see fr.n7.jEU.typevisibilite
   * @generated
   */
  EEnum gettypevisibilite();

  /**
   * Returns the meta object for enum '{@link fr.n7.jEU.typeLieu <em>type Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>type Lieu</em>'.
   * @see fr.n7.jEU.typeLieu
   * @generated
   */
  EEnum gettypeLieu();

  /**
   * Returns the meta object for enum '{@link fr.n7.jEU.ouvertOuferme <em>ouvert Ouferme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>ouvert Ouferme</em>'.
   * @see fr.n7.jEU.ouvertOuferme
   * @generated
   */
  EEnum getouvertOuferme();

  /**
   * Returns the meta object for enum '{@link fr.n7.jEU.typeactivite <em>typeactivite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>typeactivite</em>'.
   * @see fr.n7.jEU.typeactivite
   * @generated
   */
  EEnum gettypeactivite();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JEUFactory getJEUFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.n7.jEU.impl.JeuImpl <em>Jeu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.impl.JeuImpl
     * @see fr.n7.jEU.impl.JEUPackageImpl#getJeu()
     * @generated
     */
    EClass JEU = eINSTANCE.getJeu();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JEU__NAME = eINSTANCE.getJeu_Name();

    /**
     * The meta object literal for the '<em><b>Joueur</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JEU__JOUEUR = eINSTANCE.getJeu_Joueur();

    /**
     * The meta object literal for the '<em><b>Jeuelement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JEU__JEUELEMENT = eINSTANCE.getJeu_Jeuelement();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.impl.JeuElementImpl <em>Jeu Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.impl.JeuElementImpl
     * @see fr.n7.jEU.impl.JEUPackageImpl#getJeuElement()
     * @generated
     */
    EClass JEU_ELEMENT = eINSTANCE.getJeuElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JEU_ELEMENT__NAME = eINSTANCE.getJeuElement_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JEU_ELEMENT__DESCRIPTION = eINSTANCE.getJeuElement_Description();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.impl.JoueurImpl <em>Joueur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.impl.JoueurImpl
     * @see fr.n7.jEU.impl.JEUPackageImpl#getJoueur()
     * @generated
     */
    EClass JOUEUR = eINSTANCE.getJoueur();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOUEUR__NAME = eINSTANCE.getJoueur_Name();

    /**
     * The meta object literal for the '<em><b>Connaissance</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOUEUR__CONNAISSANCE = eINSTANCE.getJoueur_Connaissance();

    /**
     * The meta object literal for the '<em><b>Tailleinventaire</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOUEUR__TAILLEINVENTAIRE = eINSTANCE.getJoueur_Tailleinventaire();

    /**
     * The meta object literal for the '<em><b>Objets</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOUEUR__OBJETS = eINSTANCE.getJoueur_Objets();

    /**
     * The meta object literal for the '<em><b>Lieu</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOUEUR__LIEU = eINSTANCE.getJoueur_Lieu();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.impl.CheminImpl <em>Chemin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.impl.CheminImpl
     * @see fr.n7.jEU.impl.JEUPackageImpl#getChemin()
     * @generated
     */
    EClass CHEMIN = eINSTANCE.getChemin();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__SOURCE = eINSTANCE.getChemin_Source();

    /**
     * The meta object literal for the '<em><b>Destination</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__DESTINATION = eINSTANCE.getChemin_Destination();

    /**
     * The meta object literal for the '<em><b>Ouvert OUferme</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHEMIN__OUVERT_OUFERME = eINSTANCE.getChemin_OuvertOUferme();

    /**
     * The meta object literal for the '<em><b>Visibilite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHEMIN__VISIBILITE = eINSTANCE.getChemin_Visibilite();

    /**
     * The meta object literal for the '<em><b>Acces</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__ACCES = eINSTANCE.getChemin_Acces();

    /**
     * The meta object literal for the '<em><b>Visible</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__VISIBLE = eINSTANCE.getChemin_Visible();

    /**
     * The meta object literal for the '<em><b>Allocateurs Connaissance</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__ALLOCATEURS_CONNAISSANCE = eINSTANCE.getChemin_AllocateursConnaissance();

    /**
     * The meta object literal for the '<em><b>Allocateurs Objet Lieu</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__ALLOCATEURS_OBJET_LIEU = eINSTANCE.getChemin_AllocateursObjetLieu();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.impl.AllocateurConnaissanceImpl <em>Allocateur Connaissance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.impl.AllocateurConnaissanceImpl
     * @see fr.n7.jEU.impl.JEUPackageImpl#getAllocateurConnaissance()
     * @generated
     */
    EClass ALLOCATEUR_CONNAISSANCE = eINSTANCE.getAllocateurConnaissance();

    /**
     * The meta object literal for the '<em><b>Connaissance Alloue</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALLOCATEUR_CONNAISSANCE__CONNAISSANCE_ALLOUE = eINSTANCE.getAllocateurConnaissance_ConnaissanceAlloue();

    /**
     * The meta object literal for the '<em><b>Est Conditionne</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALLOCATEUR_CONNAISSANCE__EST_CONDITIONNE = eINSTANCE.getAllocateurConnaissance_EstConditionne();

    /**
     * The meta object literal for the '<em><b>Condition Allocution</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALLOCATEUR_CONNAISSANCE__CONDITION_ALLOCUTION = eINSTANCE.getAllocateurConnaissance_ConditionAllocution();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.impl.AllocateurObjetImpl <em>Allocateur Objet</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.impl.AllocateurObjetImpl
     * @see fr.n7.jEU.impl.JEUPackageImpl#getAllocateurObjet()
     * @generated
     */
    EClass ALLOCATEUR_OBJET = eINSTANCE.getAllocateurObjet();

    /**
     * The meta object literal for the '<em><b>Objet Alloue</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALLOCATEUR_OBJET__OBJET_ALLOUE = eINSTANCE.getAllocateurObjet_ObjetAlloue();

    /**
     * The meta object literal for the '<em><b>Consomme</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALLOCATEUR_OBJET__CONSOMME = eINSTANCE.getAllocateurObjet_Consomme();

    /**
     * The meta object literal for the '<em><b>Quantite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALLOCATEUR_OBJET__QUANTITE = eINSTANCE.getAllocateurObjet_Quantite();

    /**
     * The meta object literal for the '<em><b>Est Conditionne</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALLOCATEUR_OBJET__EST_CONDITIONNE = eINSTANCE.getAllocateurObjet_EstConditionne();

    /**
     * The meta object literal for the '<em><b>Condition Allocution</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALLOCATEUR_OBJET__CONDITION_ALLOCUTION = eINSTANCE.getAllocateurObjet_ConditionAllocution();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.impl.LieuImpl <em>Lieu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.impl.LieuImpl
     * @see fr.n7.jEU.impl.JEUPackageImpl#getLieu()
     * @generated
     */
    EClass LIEU = eINSTANCE.getLieu();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIEU__TYPE = eINSTANCE.getLieu_Type();

    /**
     * The meta object literal for the '<em><b>Connaissance</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__CONNAISSANCE = eINSTANCE.getLieu_Connaissance();

    /**
     * The meta object literal for the '<em><b>Objetslieu</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__OBJETSLIEU = eINSTANCE.getLieu_Objetslieu();

    /**
     * The meta object literal for the '<em><b>Personnes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__PERSONNES = eINSTANCE.getLieu_Personnes();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.impl.ConnaissanceImpl <em>Connaissance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.impl.ConnaissanceImpl
     * @see fr.n7.jEU.impl.JEUPackageImpl#getConnaissance()
     * @generated
     */
    EClass CONNAISSANCE = eINSTANCE.getConnaissance();

    /**
     * The meta object literal for the '<em><b>Visibilite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNAISSANCE__VISIBILITE = eINSTANCE.getConnaissance_Visibilite();

    /**
     * The meta object literal for the '<em><b>Activite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNAISSANCE__ACTIVITE = eINSTANCE.getConnaissance_Activite();

    /**
     * The meta object literal for the '<em><b>Est Possede</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNAISSANCE__EST_POSSEDE = eINSTANCE.getConnaissance_EstPossede();

    /**
     * The meta object literal for the '<em><b>Acces</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNAISSANCE__ACCES = eINSTANCE.getConnaissance_Acces();

    /**
     * The meta object literal for the '<em><b>Visible</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNAISSANCE__VISIBLE = eINSTANCE.getConnaissance_Visible();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.impl.ObjetImpl <em>Objet</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.impl.ObjetImpl
     * @see fr.n7.jEU.impl.JEUPackageImpl#getObjet()
     * @generated
     */
    EClass OBJET = eINSTANCE.getObjet();

    /**
     * The meta object literal for the '<em><b>Taille</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__TAILLE = eINSTANCE.getObjet_Taille();

    /**
     * The meta object literal for the '<em><b>Quantite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__QUANTITE = eINSTANCE.getObjet_Quantite();

    /**
     * The meta object literal for the '<em><b>Visibilite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__VISIBILITE = eINSTANCE.getObjet_Visibilite();

    /**
     * The meta object literal for the '<em><b>Activite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__ACTIVITE = eINSTANCE.getObjet_Activite();

    /**
     * The meta object literal for the '<em><b>Dans Lieu</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__DANS_LIEU = eINSTANCE.getObjet_DansLieu();

    /**
     * The meta object literal for the '<em><b>Lieu</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET__LIEU = eINSTANCE.getObjet_Lieu();

    /**
     * The meta object literal for the '<em><b>Condition Deposer</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET__CONDITION_DEPOSER = eINSTANCE.getObjet_ConditionDeposer();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.impl.InteractionImpl <em>Interaction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.impl.InteractionImpl
     * @see fr.n7.jEU.impl.JEUPackageImpl#getInteraction()
     * @generated
     */
    EClass INTERACTION = eINSTANCE.getInteraction();

    /**
     * The meta object literal for the '<em><b>Personne</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERACTION__PERSONNE = eINSTANCE.getInteraction_Personne();

    /**
     * The meta object literal for the '<em><b>Question</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERACTION__QUESTION = eINSTANCE.getInteraction_Question();

    /**
     * The meta object literal for the '<em><b>Choix</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERACTION__CHOIX = eINSTANCE.getInteraction_Choix();

    /**
     * The meta object literal for the '<em><b>Choix Joueur</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERACTION__CHOIX_JOUEUR = eINSTANCE.getInteraction_ChoixJoueur();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.impl.conditionImpl <em>condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.impl.conditionImpl
     * @see fr.n7.jEU.impl.JEUPackageImpl#getcondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getcondition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__NAME = eINSTANCE.getcondition_Name();

    /**
     * The meta object literal for the '<em><b>Objet</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__OBJET = eINSTANCE.getcondition_Objet();

    /**
     * The meta object literal for the '<em><b>Comparaison</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__COMPARAISON = eINSTANCE.getcondition_Comparaison();

    /**
     * The meta object literal for the '<em><b>Reference</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__REFERENCE = eINSTANCE.getcondition_Reference();

    /**
     * The meta object literal for the '<em><b>Connaissance</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__CONNAISSANCE = eINSTANCE.getcondition_Connaissance();

    /**
     * The meta object literal for the '<em><b>Presente</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__PRESENTE = eINSTANCE.getcondition_Presente();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.impl.PersonneImpl <em>Personne</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.impl.PersonneImpl
     * @see fr.n7.jEU.impl.JEUPackageImpl#getPersonne()
     * @generated
     */
    EClass PERSONNE = eINSTANCE.getPersonne();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSONNE__NAME = eINSTANCE.getPersonne_Name();

    /**
     * The meta object literal for the '<em><b>Visibilite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSONNE__VISIBILITE = eINSTANCE.getPersonne_Visibilite();

    /**
     * The meta object literal for the '<em><b>Activite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSONNE__ACTIVITE = eINSTANCE.getPersonne_Activite();

    /**
     * The meta object literal for the '<em><b>Interaction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSONNE__INTERACTION = eINSTANCE.getPersonne_Interaction();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.impl.choixImpl <em>choix</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.impl.choixImpl
     * @see fr.n7.jEU.impl.JEUPackageImpl#getchoix()
     * @generated
     */
    EClass CHOIX = eINSTANCE.getchoix();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOIX__NAME = eINSTANCE.getchoix_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOIX__DESCRIPTION = eINSTANCE.getchoix_Description();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOIX__ACTIONS = eINSTANCE.getchoix_Actions();

    /**
     * The meta object literal for the '<em><b>Est Fin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOIX__EST_FIN = eINSTANCE.getchoix_EstFin();

    /**
     * The meta object literal for the '<em><b>Condition Fin</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOIX__CONDITION_FIN = eINSTANCE.getchoix_ConditionFin();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.impl.actionImpl <em>action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.impl.actionImpl
     * @see fr.n7.jEU.impl.JEUPackageImpl#getaction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getaction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__NAME = eINSTANCE.getaction_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__DESCRIPTION = eINSTANCE.getaction_Description();

    /**
     * The meta object literal for the '<em><b>Allocateurs Connaissance</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__ALLOCATEURS_CONNAISSANCE = eINSTANCE.getaction_AllocateursConnaissance();

    /**
     * The meta object literal for the '<em><b>Allocateurs Objet Lieu</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__ALLOCATEURS_OBJET_LIEU = eINSTANCE.getaction_AllocateursObjetLieu();

    /**
     * The meta object literal for the '<em><b>Condition Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__CONDITION_ACTION = eINSTANCE.getaction_ConditionAction();

    /**
     * The meta object literal for the '<em><b>Choix Suivants</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__CHOIX_SUIVANTS = eINSTANCE.getaction_ChoixSuivants();

    /**
     * The meta object literal for the '<em><b>Est Finale</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__EST_FINALE = eINSTANCE.getaction_EstFinale();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.Comparateur <em>Comparateur</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.Comparateur
     * @see fr.n7.jEU.impl.JEUPackageImpl#getComparateur()
     * @generated
     */
    EEnum COMPARATEUR = eINSTANCE.getComparateur();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.typevisibilite <em>typevisibilite</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.typevisibilite
     * @see fr.n7.jEU.impl.JEUPackageImpl#gettypevisibilite()
     * @generated
     */
    EEnum TYPEVISIBILITE = eINSTANCE.gettypevisibilite();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.typeLieu <em>type Lieu</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.typeLieu
     * @see fr.n7.jEU.impl.JEUPackageImpl#gettypeLieu()
     * @generated
     */
    EEnum TYPE_LIEU = eINSTANCE.gettypeLieu();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.ouvertOuferme <em>ouvert Ouferme</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.ouvertOuferme
     * @see fr.n7.jEU.impl.JEUPackageImpl#getouvertOuferme()
     * @generated
     */
    EEnum OUVERT_OUFERME = eINSTANCE.getouvertOuferme();

    /**
     * The meta object literal for the '{@link fr.n7.jEU.typeactivite <em>typeactivite</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.jEU.typeactivite
     * @see fr.n7.jEU.impl.JEUPackageImpl#gettypeactivite()
     * @generated
     */
    EEnum TYPEACTIVITE = eINSTANCE.gettypeactivite();

  }

} //JEUPackage
