/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Joueur</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jEU.Joueur#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.jEU.Joueur#getConnaissance <em>Connaissance</em>}</li>
 *   <li>{@link fr.n7.jEU.Joueur#getTailleinventaire <em>Tailleinventaire</em>}</li>
 *   <li>{@link fr.n7.jEU.Joueur#getObjets <em>Objets</em>}</li>
 *   <li>{@link fr.n7.jEU.Joueur#getLieu <em>Lieu</em>}</li>
 * </ul>
 *
 * @see fr.n7.jEU.JEUPackage#getJoueur()
 * @model
 * @generated
 */
public interface Joueur extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.jEU.JEUPackage#getJoueur_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Joueur#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Connaissance</b></em>' reference list.
   * The list contents are of type {@link fr.n7.jEU.Connaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connaissance</em>' reference list.
   * @see fr.n7.jEU.JEUPackage#getJoueur_Connaissance()
   * @model
   * @generated
   */
  EList<Connaissance> getConnaissance();

  /**
   * Returns the value of the '<em><b>Tailleinventaire</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tailleinventaire</em>' attribute.
   * @see #setTailleinventaire(int)
   * @see fr.n7.jEU.JEUPackage#getJoueur_Tailleinventaire()
   * @model
   * @generated
   */
  int getTailleinventaire();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Joueur#getTailleinventaire <em>Tailleinventaire</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tailleinventaire</em>' attribute.
   * @see #getTailleinventaire()
   * @generated
   */
  void setTailleinventaire(int value);

  /**
   * Returns the value of the '<em><b>Objets</b></em>' reference list.
   * The list contents are of type {@link fr.n7.jEU.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objets</em>' reference list.
   * @see fr.n7.jEU.JEUPackage#getJoueur_Objets()
   * @model
   * @generated
   */
  EList<Objet> getObjets();

  /**
   * Returns the value of the '<em><b>Lieu</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lieu</em>' reference.
   * @see #setLieu(Lieu)
   * @see fr.n7.jEU.JEUPackage#getJoueur_Lieu()
   * @model
   * @generated
   */
  Lieu getLieu();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Joueur#getLieu <em>Lieu</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lieu</em>' reference.
   * @see #getLieu()
   * @generated
   */
  void setLieu(Lieu value);

} // Joueur
