/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lieu</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jEU.Lieu#getType <em>Type</em>}</li>
 *   <li>{@link fr.n7.jEU.Lieu#getConnaissance <em>Connaissance</em>}</li>
 *   <li>{@link fr.n7.jEU.Lieu#getObjetslieu <em>Objetslieu</em>}</li>
 *   <li>{@link fr.n7.jEU.Lieu#getPersonnes <em>Personnes</em>}</li>
 * </ul>
 *
 * @see fr.n7.jEU.JEUPackage#getLieu()
 * @model
 * @generated
 */
public interface Lieu extends JeuElement
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.jEU.typeLieu}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see fr.n7.jEU.typeLieu
   * @see #setType(typeLieu)
   * @see fr.n7.jEU.JEUPackage#getLieu_Type()
   * @model
   * @generated
   */
  typeLieu getType();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Lieu#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see fr.n7.jEU.typeLieu
   * @see #getType()
   * @generated
   */
  void setType(typeLieu value);

  /**
   * Returns the value of the '<em><b>Connaissance</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jEU.Connaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connaissance</em>' containment reference list.
   * @see fr.n7.jEU.JEUPackage#getLieu_Connaissance()
   * @model containment="true"
   * @generated
   */
  EList<Connaissance> getConnaissance();

  /**
   * Returns the value of the '<em><b>Objetslieu</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jEU.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objetslieu</em>' containment reference list.
   * @see fr.n7.jEU.JEUPackage#getLieu_Objetslieu()
   * @model containment="true"
   * @generated
   */
  EList<Objet> getObjetslieu();

  /**
   * Returns the value of the '<em><b>Personnes</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.jEU.Personne}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Personnes</em>' containment reference list.
   * @see fr.n7.jEU.JEUPackage#getLieu_Personnes()
   * @model containment="true"
   * @generated
   */
  EList<Personne> getPersonnes();

} // Lieu
