/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Objet</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jEU.Objet#getTaille <em>Taille</em>}</li>
 *   <li>{@link fr.n7.jEU.Objet#getQuantite <em>Quantite</em>}</li>
 *   <li>{@link fr.n7.jEU.Objet#getVisibilite <em>Visibilite</em>}</li>
 *   <li>{@link fr.n7.jEU.Objet#getActivite <em>Activite</em>}</li>
 *   <li>{@link fr.n7.jEU.Objet#isDansLieu <em>Dans Lieu</em>}</li>
 *   <li>{@link fr.n7.jEU.Objet#getLieu <em>Lieu</em>}</li>
 *   <li>{@link fr.n7.jEU.Objet#getConditionDeposer <em>Condition Deposer</em>}</li>
 * </ul>
 *
 * @see fr.n7.jEU.JEUPackage#getObjet()
 * @model
 * @generated
 */
public interface Objet extends JeuElement
{
  /**
   * Returns the value of the '<em><b>Taille</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Taille</em>' attribute.
   * @see #setTaille(int)
   * @see fr.n7.jEU.JEUPackage#getObjet_Taille()
   * @model
   * @generated
   */
  int getTaille();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Objet#getTaille <em>Taille</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Taille</em>' attribute.
   * @see #getTaille()
   * @generated
   */
  void setTaille(int value);

  /**
   * Returns the value of the '<em><b>Quantite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantite</em>' attribute.
   * @see #setQuantite(int)
   * @see fr.n7.jEU.JEUPackage#getObjet_Quantite()
   * @model
   * @generated
   */
  int getQuantite();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Objet#getQuantite <em>Quantite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantite</em>' attribute.
   * @see #getQuantite()
   * @generated
   */
  void setQuantite(int value);

  /**
   * Returns the value of the '<em><b>Visibilite</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.jEU.typevisibilite}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visibilite</em>' attribute.
   * @see fr.n7.jEU.typevisibilite
   * @see #setVisibilite(typevisibilite)
   * @see fr.n7.jEU.JEUPackage#getObjet_Visibilite()
   * @model
   * @generated
   */
  typevisibilite getVisibilite();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Objet#getVisibilite <em>Visibilite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visibilite</em>' attribute.
   * @see fr.n7.jEU.typevisibilite
   * @see #getVisibilite()
   * @generated
   */
  void setVisibilite(typevisibilite value);

  /**
   * Returns the value of the '<em><b>Activite</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.jEU.typeactivite}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activite</em>' attribute.
   * @see fr.n7.jEU.typeactivite
   * @see #setActivite(typeactivite)
   * @see fr.n7.jEU.JEUPackage#getObjet_Activite()
   * @model
   * @generated
   */
  typeactivite getActivite();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Objet#getActivite <em>Activite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Activite</em>' attribute.
   * @see fr.n7.jEU.typeactivite
   * @see #getActivite()
   * @generated
   */
  void setActivite(typeactivite value);

  /**
   * Returns the value of the '<em><b>Dans Lieu</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dans Lieu</em>' attribute.
   * @see #setDansLieu(boolean)
   * @see fr.n7.jEU.JEUPackage#getObjet_DansLieu()
   * @model
   * @generated
   */
  boolean isDansLieu();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Objet#isDansLieu <em>Dans Lieu</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dans Lieu</em>' attribute.
   * @see #isDansLieu()
   * @generated
   */
  void setDansLieu(boolean value);

  /**
   * Returns the value of the '<em><b>Lieu</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lieu</em>' reference.
   * @see #setLieu(Lieu)
   * @see fr.n7.jEU.JEUPackage#getObjet_Lieu()
   * @model
   * @generated
   */
  Lieu getLieu();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Objet#getLieu <em>Lieu</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lieu</em>' reference.
   * @see #getLieu()
   * @generated
   */
  void setLieu(Lieu value);

  /**
   * Returns the value of the '<em><b>Condition Deposer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition Deposer</em>' containment reference.
   * @see #setConditionDeposer(condition)
   * @see fr.n7.jEU.JEUPackage#getObjet_ConditionDeposer()
   * @model containment="true"
   * @generated
   */
  condition getConditionDeposer();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Objet#getConditionDeposer <em>Condition Deposer</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition Deposer</em>' containment reference.
   * @see #getConditionDeposer()
   * @generated
   */
  void setConditionDeposer(condition value);

} // Objet
