/**
 * generated by Xtext 2.17.1
 */
package fr.n7.jEU;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Personne</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.jEU.Personne#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.jEU.Personne#getVisibilite <em>Visibilite</em>}</li>
 *   <li>{@link fr.n7.jEU.Personne#getActivite <em>Activite</em>}</li>
 *   <li>{@link fr.n7.jEU.Personne#getInteraction <em>Interaction</em>}</li>
 * </ul>
 *
 * @see fr.n7.jEU.JEUPackage#getPersonne()
 * @model
 * @generated
 */
public interface Personne extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.jEU.JEUPackage#getPersonne_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Personne#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Visibilite</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.jEU.typevisibilite}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visibilite</em>' attribute.
   * @see fr.n7.jEU.typevisibilite
   * @see #setVisibilite(typevisibilite)
   * @see fr.n7.jEU.JEUPackage#getPersonne_Visibilite()
   * @model
   * @generated
   */
  typevisibilite getVisibilite();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Personne#getVisibilite <em>Visibilite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visibilite</em>' attribute.
   * @see fr.n7.jEU.typevisibilite
   * @see #getVisibilite()
   * @generated
   */
  void setVisibilite(typevisibilite value);

  /**
   * Returns the value of the '<em><b>Activite</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.jEU.typeactivite}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activite</em>' attribute.
   * @see fr.n7.jEU.typeactivite
   * @see #setActivite(typeactivite)
   * @see fr.n7.jEU.JEUPackage#getPersonne_Activite()
   * @model
   * @generated
   */
  typeactivite getActivite();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Personne#getActivite <em>Activite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Activite</em>' attribute.
   * @see fr.n7.jEU.typeactivite
   * @see #getActivite()
   * @generated
   */
  void setActivite(typeactivite value);

  /**
   * Returns the value of the '<em><b>Interaction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interaction</em>' containment reference.
   * @see #setInteraction(Interaction)
   * @see fr.n7.jEU.JEUPackage#getPersonne_Interaction()
   * @model containment="true"
   * @generated
   */
  Interaction getInteraction();

  /**
   * Sets the value of the '{@link fr.n7.jEU.Personne#getInteraction <em>Interaction</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interaction</em>' containment reference.
   * @see #getInteraction()
   * @generated
   */
  void setInteraction(Interaction value);

} // Personne
