/*
 * generated by Xtext 2.17.1
 */
package fr.n7.ide

import com.google.inject.Guice
import fr.n7.JEURuntimeModule
import fr.n7.JEUStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class JEUIdeSetup extends JEUStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new JEURuntimeModule, new JEUIdeModule))
	}
	
}
