/*
 * generated by Xtext 2.17.1
 */
package fr.n7


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class JEUStandaloneSetup extends JEUStandaloneSetupGenerated {

	def static void doSetup() {
		new JEUStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
